name: Test GhostComment Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  test-ghostcomment:
    runs-on: ubuntu-latest
    name: Test GhostComment Action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run GhostComment (Published Action)
        uses: jamesurobertson/ghostcomment@v1.0.2 # Uses bundled GitHub Action
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          config-path: ".ghostcommentrc"
          fail-on-found: false
          clean-mode: true
          dry-run: false
          verbose: true
